version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-n8n}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
      # Reduce memory usage for better performance
      - NODE_OPTIONS=--max-old-space-size=512
      # Skip waiting for InfluxDB
      - WAIT_HOSTS_TIMEOUT=30
    volumes:
      - n8n_data:/home/node/.n8n
    # Use healthcheck to ensure n8n is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - n8n-network

  influxdb:
    image: influxdb:2.7
    restart: always
    ports:
      - "8087:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-adminpassword}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-myorg}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-sensors}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-auth-token}
      # Performance optimizations
      - INFLUXD_BOLT_PATH=/var/lib/influxdb2/influxd.bolt
      - INFLUXD_ENGINE_PATH=/var/lib/influxdb2/engine
      # Reduce memory usage
      - INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE=256MB
    volumes:
      - influxdb_data:/var/lib/influxdb2
    # Use healthcheck to ensure InfluxDB is running properly
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data:
  influxdb_data:
